" colorscheme management
colorscheme vilight
"map <F5> :colorscheme torte<CR>
"map <F6> :colorscheme refactor<CR>
"map <F7> :colorscheme vilight<CR>
"map <F8> :colorscheme default<CR>

" making gvim usable
set guioptions-=m
set guioptions-=T

