#!/bin/sh
###############################################################################
##
##  Create a SOCKS5 proxy and forward SMTP port
##
###############################################################################

ssh -D 4223 -fN -L localhost:2525:chaossource.net:25 chaossource.net

